export type Provider = 'aws' | 'azure';
export type RegionStatus = 'idle' | 'warmup' | 'measuring' | 'done' | 'error';

export interface Region {
  id: string;
  code: string;
  city: string;
  flag: string;
  provider: Provider;
  endpoint: string;
  latency: number | null;
  prevLatency: number | null;
  status: RegionStatus;
  samples: number[];
}

export const INITIAL_REGIONS: Region[] = [
  // ── AWS ─────────────────────────────────────────────────────────────
  {
    id: 'aws-us-east-1',
    code: 'us-east-1',
    city: 'N. Virginia',
    flag: '🇺🇸',
    provider: 'aws',
    endpoint: 'https://s3.us-east-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-us-west-2',
    code: 'us-west-2',
    city: 'Oregon',
    flag: '🇺🇸',
    provider: 'aws',
    endpoint: 'https://s3.us-west-2.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-eu-west-1',
    code: 'eu-west-1',
    city: 'Ireland',
    flag: '🇮🇪',
    provider: 'aws',
    endpoint: 'https://s3.eu-west-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-eu-central-1',
    code: 'eu-central-1',
    city: 'Frankfurt',
    flag: '🇩🇪',
    provider: 'aws',
    endpoint: 'https://s3.eu-central-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-ap-southeast-1',
    code: 'ap-southeast-1',
    city: 'Singapore',
    flag: '🇸🇬',
    provider: 'aws',
    endpoint: 'https://s3.ap-southeast-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-ap-northeast-1',
    code: 'ap-northeast-1',
    city: 'Tokyo',
    flag: '🇯🇵',
    provider: 'aws',
    endpoint: 'https://s3.ap-northeast-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-ap-south-1',
    code: 'ap-south-1',
    city: 'Mumbai',
    flag: '🇮🇳',
    provider: 'aws',
    endpoint: 'https://s3.ap-south-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-sa-east-1',
    code: 'sa-east-1',
    city: 'São Paulo',
    flag: '🇧🇷',
    provider: 'aws',
    endpoint: 'https://s3.sa-east-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-ca-central-1',
    code: 'ca-central-1',
    city: 'Canada Central',
    flag: '🇨🇦',
    provider: 'aws',
    endpoint: 'https://s3.ca-central-1.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'aws-ap-southeast-2',
    code: 'ap-southeast-2',
    city: 'Sydney',
    flag: '🇦🇺',
    provider: 'aws',
    endpoint: 'https://s3.ap-southeast-2.amazonaws.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  // ── AZURE ───────────────────────────────────────────────────────────
  {
    id: 'az-eastus',
    code: 'eastus',
    city: 'Virginia',
    flag: '🇺🇸',
    provider: 'azure',
    endpoint: 'https://eastus.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-westus2',
    code: 'westus2',
    city: 'Washington',
    flag: '🇺🇸',
    provider: 'azure',
    endpoint: 'https://westus2.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-westeurope',
    code: 'westeurope',
    city: 'Netherlands',
    flag: '🇳🇱',
    provider: 'azure',
    endpoint: 'https://westeurope.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-germanywestcentral',
    code: 'germanywestcentral',
    city: 'Frankfurt',
    flag: '🇩🇪',
    provider: 'azure',
    endpoint: 'https://germanywestcentral.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-southeastasia',
    code: 'southeastasia',
    city: 'Singapore',
    flag: '🇸🇬',
    provider: 'azure',
    endpoint: 'https://southeastasia.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-japaneast',
    code: 'japaneast',
    city: 'Tokyo',
    flag: '🇯🇵',
    provider: 'azure',
    endpoint: 'https://japaneast.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-centralindia',
    code: 'centralindia',
    city: 'Pune',
    flag: '🇮🇳',
    provider: 'azure',
    endpoint: 'https://centralindia.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-brazilsouth',
    code: 'brazilsouth',
    city: 'São Paulo',
    flag: '🇧🇷',
    provider: 'azure',
    endpoint: 'https://brazilsouth.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-canadacentral',
    code: 'canadacentral',
    city: 'Toronto',
    flag: '🇨🇦',
    provider: 'azure',
    endpoint: 'https://canadacentral.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
  {
    id: 'az-australiaeast',
    code: 'australiaeast',
    city: 'Sydney',
    flag: '🇦🇺',
    provider: 'azure',
    endpoint: 'https://australiaeast.api.cognitive.microsoft.com',
    latency: null,
    prevLatency: null,
    status: 'idle',
    samples: [],
  },
];
